const DRAFT_RECOMMENDATION_URL = "https://2026-fantasy-rankings.vercel.app/api/gemini-advice";

/**
 * Request a concise fantasy draft recommendation from the Vercel backend.
 * The Gemini API key remains server-side in Vercel environment variables.
 *
 * @param {object} contextPayload Draft context generated by draftEngine.js.
 * @returns {Promise<object>} Structured draft advice.
 */
export async function getAIRecommendation(contextPayload) {
  let response;
  try {
    response = await fetch(DRAFT_RECOMMENDATION_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ contextPayload }),
    });
  } catch (error) {
    throw new Error(`Unable to reach the draft recommendation service: ${error?.message || "Network request failed."}`);
  }

  let result;
  try {
    result = await response.json();
  } catch {
    throw new Error("The draft recommendation service returned an invalid response.");
  }

  if (!response.ok) {
    throw new Error(result?.error || `Draft recommendation request failed with status ${response.status}.`);
  }

  const recommendation = result?.analysis && typeof result.analysis === "object"
    ? result.analysis
    : result;
  const requiredFields = ["recommendedPlayer", "strategy", "turnRiskAnalysis", "rosterContext"];
  if (!requiredFields.every(
    (field) => typeof recommendation?.[field] === "string" && recommendation[field].trim(),
  )) {
    throw new Error("The draft recommendation service returned an empty recommendation.");
  }

  return Object.fromEntries(requiredFields.map((field) => [field, recommendation[field].trim()]));
}
